import { Download } from "lucide-react";
import { CoordinatorState, normalizedStudents, useCoordinatorData } from "./coordinatorData.jsx";

function OjtReports() {
  const { data, loading, error } = useCoordinatorData();
  const students = normalizedStudents(data.students, data.attendance);
  const pendingEvaluations = data.evaluations.filter((item) => String(item.status || "").toLowerCase() !== "completed").length;
  const exportCsv = () => { const rows = [["Student", "Company", "Completed Hours", "Required Hours", "Status", "Evaluation Status"], ...students.map((item) => [item.name, item.company, item.completed, item.required, item.status, data.evaluations.some((evaluation) => evaluation.studentId === item.studentId && evaluation.status === "Completed") ? "Completed" : "Pending"])]; const blob = new Blob([rows.map((row) => row.join(",")).join("\n")], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "ojt-report.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <CoordinatorState loading={loading} error={error}><main className="coordinator-data-page"><header className="coordinator-data-header"><div><p>OJT reporting</p><h1>OJT Reports</h1><span>Student progress, attendance hours, and evaluation status.</span></div><button type="button" className="coordinator-primary-button" onClick={exportCsv}><Download size={16} /> Export CSV</button></header><section className="coordinator-report-summary"><article><strong>{students.length}</strong><span>Students</span></article><article><strong>{students.reduce((sum, item) => sum + item.completed, 0)}</strong><span>Completed hours</span></article><article><strong>{data.attendance.length}</strong><span>Attendance records</span></article><article><strong>{pendingEvaluations}</strong><span>Pending evaluations</span></article></section><section className="coordinator-data-panel"><div className="coordinator-data-table-wrap"><table className="coordinator-data-table"><thead><tr><th>Student</th><th>Company</th><th>Hours</th><th>Attendance</th><th>Evaluation</th><th>Status</th></tr></thead><tbody>{students.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.studentId}</small></td><td>{item.company}</td><td>{item.completed} / {item.required}</td><td>{data.attendance.filter((record) => record.studentId === item.studentId).length} records</td><td>{data.evaluations.some((record) => record.studentId === item.studentId && record.status === "Completed") ? "Completed" : "Pending"}</td><td>{item.status}</td></tr>)}</tbody></table>{students.length === 0 && <div className="coordinator-data-empty">No report data is available.</div>}</div></section></main></CoordinatorState>;
}

export default OjtReports;
